### ISSUE TITLE
barChart  实现换行  只显示一行，请问柱状图怎么实现换行

### ISSUE THREAD

**Issue by ltpostbox** [SouthernBox/MPAndroidChart-Newline#1]
barChart  实现换行  只显示一行，请问柱状图怎么实现换行

**Comment by NanBox** [comment]
是不是第二行没显示？还是没有换行？

**Comment by ltpostbox** [comment]
第二行直接就看不到  因为第一行文字最下边没显示全  是因为什么原因？

**Comment by NanBox** [comment]
要用 setViewPortOffsets(float left, float top, float right, float bottom) 增加图表下面的距离，bottom 的值越大，下面可显示的高度就越大。

**Comment by ltpostbox** [comment]
@SouthernBox  刚才试了 有用 谢谢楼主！

**Comment by NanBox** [comment]
不客气
